development:
  adapter: postgresql
  encoding: unicode
  database: farmerce_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: farmerce_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: farmerce_production
  pool: 5
  username: postgres
  password: postgres